### ISSUE TITLE
Install issues 

### ISSUE THREAD

**Issue by preetida** [KrishnaswamyLab/TrajectoryNet#18]
Hello, 
I have time-series scRNA data that I want to analyze with Trajectory Net. 
I am trying to install TrajecetoryNet and I am getting following error 
```
!pip3 install TrajectoryNet
import TrajectoryNet
!python3 -m TrajectoryNet.main --dataset EB
```
Below is the error :
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/TrajectoryNet/main.py", line 16, in <module>
    from TrajectoryNet.lib.growth_net import GrowthNet
ModuleNotFoundError: No module named 'TrajectoryNet.lib'
1

```

**Comment by atong01** [comment]
Hi @preetida,

Thanks for bringing this to my attention this is now fixed in #19. Please `pip install --upgrade TrajectoryNet` to version `0.2.4`.
