### ISSUE TITLE
Can't run the ReadMe example

### ISSUE THREAD

**Issue by Dharmesh946** [KrishnaswamyLab/TrajectoryNet#23]
As stated in the readme I executed the following commands in a terminal, Ubuntu 22:
```
pip install TrajectoryNet
python3 -m TrajectoryNet.main --dataset SCURVE
```

The first line succedeed but on running the script I've got:
```
True
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/<user>/.local/lib/python3.10/site-packages/TrajectoryNet/main.py", line 516, in <module>
    main(args)
  File "/home/<user>/.local/lib/python3.10/site-packages/TrajectoryNet/main.py", line 433, in main
    utils.makedirs(args.save)
  File "/home/<user>/.local/lib/python3.10/site-packages/TrajectoryNet/lib/utils.py", line 10, in makedirs
    os.makedirs(dirname)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '../results'
```

My guess is that the script needs a ../results directory that is trying to create (from what location?) but it needs special rights.

**Comment by atong01** [comment]
Hi!

Yes, normally this code expects permissions to be able to make a results directory in the directory above its current working directory. This is configured with the `--save` argument. If you specify a place where you have write permissions this should work in your case.

**Comment by Dharmesh946** [comment]
Thanks, `--save` was required.

IMHO, the documentation of this option is not sufficient and it should be mentioned in the readme.md.
